### ISSUE TITLE
Wrong tag names: 0.7.1 -> v0.7.1

### ISSUE THREAD

**Issue by oprypin** [woodruffw/x_do.cr#1] opened 2018-08-12 11:26 UTC
`shards install` expects the tag `v0.7.1` when specifying `version: 0.7.1`. Please start by duplicating the latest tag and then switch to the correct scheme.

**Comment by woodruffw** [comment] 2018-08-12 14:13
Sure; thanks for the heads up.

Was this caused by a change in `shards`? I recall this working before.

**Comment by woodruffw** [comment] 2018-08-12 14:16
Fixed by https://github.com/woodruffw/x_do.cr/commit/3c5aea5e5073ba01ab82aaabdedf26e8b34873dc.

**Closed as completed by woodruffw** 2018-08-12 14:16 UTC
